version: '3.8'

services:
  moodle:
    image: bitnami/moodle:5.0.0-debian-12-r3
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.conf.tls=true"
        - "traefik.http.routers.conf.tls.certresolver=confresolver"
        - "traefik.http.routers.conf.rule=Host(`conf.td-aurora.ru`)"
        - "traefik.http.services.conf.loadbalancer.server.port=80"
 
    ports:
      - "8080:80"
    environment:
      MOODLE_DATABASE_TYPE: mariadb
      MOODLE_DATABASE_HOST: moodle_db
      MOODLE_DATABASE_PORT_NUMBER: 3306
      MOODLE_DATABASE_USER: moodle
      MOODLE_DATABASE_NAME: moodle
      MOODLE_DATABASE_PASSWORD: moodlepassword
      MOODLE_USERNAME: admin
      MOODLE_PASSWORD: adminpassword
      MOODLE_EMAIL: anton@td-aurora.ru
      MOODLE_SITE_NAME: My Moodle Site
    volumes:
      - moodle_data:/bitnami/moodle
    networks:
      - moodle_network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
  moodle_db:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodle
      MYSQL_PASSWORD: moodlepassword
    volumes:
      - db_data:/bitnami/mariadb
    networks:
      - moodle_network
    deploy:
      placement:
        constraints: [node.role == manager]

volumes:
  moodle_data:
    driver: local
  db_data:
    driver: local

networks:
  moodle_network:
    driver: overlay
